$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: water-potability-online
model: azureml:water-model@latest
instance_type: Standard_DS3_v2
instance_count: 1
